### ISSUE TITLE
Plugin breaks sourcemaps

### ISSUE THREAD

**Issue by philipp-tailor** [mustafadalga/remove-attr#1]
For context: I'm talking about a Vue app built with Vite `5.0.12`, with the following plugin configuration:

```js
// vite.config.js
export default defineConfig(async ({command, mode}) => {
	const config = {
            // ... my other config
	}

	if (command === 'build' && mode === 'production') {
		const removeAttr = (await import('remove-attr')).default
		config.plugins.push(
			removeAttr({
				extensions: ['vue'],
				attributes: ['data-test'],
			})
		)
	}

	return config
})
```

When building, I'm getting the following error message - seemingly repeated for every single affected `.vue` file:

`(remove-attributes plugin) Sourcemap is likely to be incorrect: a plugin (remove-attributes) was used to transform files, but didn't generate a sourcemap for the transformation. Consult the plugin documentation for help`

The sourcemaps of all files, even JS files which aren't even affected by the plugin look as follows:

`{"version":3,"file":"myFile.js","sources":[],"sourcesContent":[],"names":[],"mappings":";;;;;;;;;;;;;;"}`

When I uncomment `remove-attr`, valid sourcemaps are being generated.

**Comment by Oleksii14** [comment]
Same here. I found [this commit](https://github.com/vuetifyjs/vuetify-loader/commit/dfdc815ad175df9ffd8be5c4847d8fe29e442f39) in the Vuetify repo that fixed the same issue there. I think we need to add something like that in [this file](https://github.com/mustafadalga/remove-attr/blob/main/src/utilities.ts#L130):

```
return { code: output, map: null };
```

**Comment by Oleksii14** [comment]
**Workaround**

```ts
import removeAttr from 'remove-attr';

const removeAttrPlugin = removeAttr({
  extensions: ['vue'],
  attributes: ['data-testid'],
});

export default {
  ...removeAttrPlugin,
  transform(code, id) {
    const result = removeAttrPlugin.transform(code, id);
    return {
      code: result,
      map: null,
    };
  },
};
```

And vite.config

```ts
import removeAttr from './vite-remove-attr-plugin';

export default {
  ...,
  plugins: [removeAttr]
}
```

**Comment by mustafadalga** [comment]
@philipp-tailor   I checked with  vite@5.0.12 and vue@3.4.29 but I could not see same error. 
Can you provide reproducible example
