### ISSUE TITLE
GPL 3 Licence too restricitve for commercial applications

### ISSUE THREAD

**Issue by vatula** [mustafadalga/remove-attr#2]
Good day Mustafa

Is it likely for the license to be changed to something more permissive, like BSD, MIT, Apache or the like? The GPL 3 triggers alerts in commercial systems and devs have to re-implement the functionality rather than use the good tested solution.

Completely understand and respect the decision to stick to GPL 3.0 if you do so.

**Comment by mustafadalga** [comment]
Hi @vatula , I can change to MIT. is it okay for you ?

**Comment by vatula** [comment]
> Hi @vatula , I can change to MIT. is it okay for you ?

Yes! 👍

**Comment by mustafadalga** [comment]
I have updated @vatula .
